- name: Create Portainer data volume on manager
  community.docker.docker_volume:
    name: portainer_data

- name: Deploy Portainer Stack
  community.docker.docker_stack:
    name: portainer
    state: present
    compose:
      - |
        version: '3.8'
        services:
          agent:
            image: portainer/agent:latest
            volumes:
              - /var/run/docker.sock:/var/run/docker.sock
              - /var/lib/docker/volumes:/var/lib/docker/volumes
            deploy:
              mode: global

          portainer:
            image: portainer/portainer-ce:latest
            ports:
              - '9000:9000'
            volumes:
              - portainer_data:/data
            deploy:
              replicas: 1
              placement:
                constraints:
                  - node.hostname == sbc
